// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sia.Data.Incidents;
using System;

namespace Sia.Data.Incidents.Migrations
{
    [DbContext(typeof(IncidentContext))]
    [Migration("20171102171453_addEventDataColumn")]
    partial class addEventDataColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sia.Data.Incidents.Models.Engagement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("IncidentId");

                    b.Property<string>("ParticipantAlias");

                    b.Property<string>("ParticipantRole");

                    b.Property<string>("ParticipantTeam");

                    b.Property<DateTime?>("TimeDisengaged");

                    b.Property<DateTime>("TimeEngaged");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("ParticipantAlias", "ParticipantTeam", "ParticipantRole");

                    b.ToTable("Engagements");
                });

            modelBuilder.Entity("Sia.Data.Incidents.Models.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("EventFired");

                    b.Property<long>("EventTypeId");

                    b.Property<long?>("IncidentId");

                    b.Property<DateTime>("Occurred");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Sia.Data.Incidents.Models.Incident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Sia.Data.Incidents.Models.Participant", b =>
                {
                    b.Property<string>("Alias");

                    b.Property<string>("Team");

                    b.Property<string>("Role");

                    b.HasKey("Alias", "Team", "Role");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Sia.Data.Incidents.Models.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("IncidentId");

                    b.Property<bool>("IsPrimary");

                    b.Property<string>("OriginId");

                    b.Property<long>("TicketingSystemId");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("TicketingSystemId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Sia.Data.Incidents.Models.TicketingSystem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TicketingSystems");
                });

            modelBuilder.Entity("Sia.Data.Incidents.Models.Engagement", b =>
                {
                    b.HasOne("Sia.Data.Incidents.Models.Incident")
                        .WithMany("Engagements")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sia.Data.Incidents.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantAlias", "ParticipantTeam", "ParticipantRole");
                });

            modelBuilder.Entity("Sia.Data.Incidents.Models.Event", b =>
                {
                    b.HasOne("Sia.Data.Incidents.Models.Incident")
                        .WithMany("Events")
                        .HasForeignKey("IncidentId");
                });

            modelBuilder.Entity("Sia.Data.Incidents.Models.Ticket", b =>
                {
                    b.HasOne("Sia.Data.Incidents.Models.Incident", "Incident")
                        .WithMany("Tickets")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sia.Data.Incidents.Models.TicketingSystem", "TicketingSystem")
                        .WithMany()
                        .HasForeignKey("TicketingSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
