language: csharp
mono: none
dotnet: 2.1.4
script:
 - dotnet restore
 - dotnet build
 - dotnet test domain/Domain/Sia.Shared.Tests/Sia.Shared.Tests.csproj
 - dotnet test test/Sia.Gateway.Tests/Sia.Gateway.Tests.csproj
